# SOME DESCRIPTIVE TITLE.
# Copyright (C) 2001-2022, Python Software Foundation
# This file is distributed under the same license as the Python package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
# Translators:
# Rafael Fontenelle <rffontenelle@gmail.com>, 2022
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: Python 3.10\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2022-12-30 14:59+0000\n"
"PO-Revision-Date: 2022-11-05 17:22+0000\n"
"Last-Translator: Rafael Fontenelle <rffontenelle@gmail.com>, 2022\n"
"Language-Team: Japanese (https://www.transifex.com/python-doc/teams/5390/"
"ja/)\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: ja\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: ../../library/urllib.error.rst:2
msgid ":mod:`urllib.error` --- Exception classes raised by urllib.request"
msgstr ":mod:`urllib.error` --- urllib.request が投げる例外"

#: ../../library/urllib.error.rst:10
msgid "**Source code:** :source:`Lib/urllib/error.py`"
msgstr "**ソースコード:** :source:`Lib/urllib/error.py`"

#: ../../library/urllib.error.rst:14
msgid ""
"The :mod:`urllib.error` module defines the exception classes for exceptions "
"raised by :mod:`urllib.request`.  The base exception class is :exc:"
"`URLError`."
msgstr ""
":mod:`urllib.error` は :mod:`urllib.request` によって投げられる例外を定義して"
"います。基底クラスは :exc:`URLError` です。"

#: ../../library/urllib.error.rst:17
msgid ""
"The following exceptions are raised by :mod:`urllib.error` as appropriate:"
msgstr ":mod:`urllib.error` は必要に応じて以下の例外が送出します:"

#: ../../library/urllib.error.rst:21
msgid ""
"The handlers raise this exception (or derived exceptions) when they run into "
"a problem.  It is a subclass of :exc:`OSError`."
msgstr ""
"ハンドラが何らかの問題に遭遇した場合、この例外 (またはこの例外から派生した例"
"外)を送出します。この例外は :exc:`OSError` のサブクラスです。"

#: ../../library/urllib.error.rst:26
msgid ""
"The reason for this error.  It can be a message string or another exception "
"instance."
msgstr "このエラーの理由。メッセージ文字列あるいは他の例外インスタンスです。"

#: ../../library/urllib.error.rst:29
msgid ""
":exc:`URLError` has been made a subclass of :exc:`OSError` instead of :exc:"
"`IOError`."
msgstr ""
":exc:`URLError` は :exc:`IOError` の代わりに :exc:`OSError` のサブクラスにな"
"りました。"

#: ../../library/urllib.error.rst:36
msgid ""
"Though being an exception (a subclass of :exc:`URLError`), an :exc:"
"`HTTPError` can also function as a non-exceptional file-like return value "
"(the same thing that :func:`~urllib.request.urlopen` returns).  This is "
"useful when handling exotic HTTP errors, such as requests for authentication."
msgstr ""
":exc:`HTTPError` は例外 (:exc:`URLError` のサブクラス) ですが、同時に例外では"
"ない file-like な戻り値を返す関数でもあります (:func:`~urllib.request."
"urlopen` の戻り値と同じです)。これは、例えばサーバからの認証リクエストのよう"
"に、変わった HTTP エラーを処理するのに役立ちます。"

#: ../../library/urllib.error.rst:44
msgid ""
"An HTTP status code as defined in :rfc:`2616`.  This numeric value "
"corresponds to a value found in the dictionary of codes as found in :attr:"
"`http.server.BaseHTTPRequestHandler.responses`."
msgstr ""
":rfc:`2616` に定義されているHTTPステータスコード。\n"
"この数値型の値は、 :attr:`http.server.BaseHTTPRequestHandler.responses` の辞"
"書に登録されているコードに対応します。"

#: ../../library/urllib.error.rst:50
msgid "This is usually a string explaining the reason for this error."
msgstr "これは通常、このエラーの原因を説明する文字列です。"

#: ../../library/urllib.error.rst:54
msgid ""
"The HTTP response headers for the HTTP request that caused the :exc:"
"`HTTPError`."
msgstr ""
":exc:`HTTPError` の原因となった HTTP リクエストの HTTP レスポンスヘッダ。"

#: ../../library/urllib.error.rst:61
msgid ""
"This exception is raised when the :func:`~urllib.request.urlretrieve` "
"function detects that the amount of the downloaded data is less than the "
"expected amount (given by the *Content-Length* header).  The :attr:`content` "
"attribute stores the downloaded (and supposedly truncated) data."
msgstr ""
"この例外は :func:`~urllib.request.urlretrieve` 関数が、ダウンロードされたデー"
"タの量が予期した量 (*Content-Length* ヘッダで与えられる) よりも少ないことを検"
"知した際に発生します。 :attr:`content` 属性には (恐らく途中までの)  ダウン"
"ロードされたデータが格納されています。"
